### PR TITLE
setup.cfg: Fix version reference

### PR DESCRIPTION
**Pull request by mkoeppe**
This fixes the error on installation:
```
      ModuleNotFoundError: No module named 'py.src'
 ```

### CODE REVIEW

**Comment by milahu** [comment]
sorry, i have reverted the merge

the current filesystem layout assumes that the package is installed from the project root
where `py.src.gnumake_tokenpool.tokenpool.__version__` should work

if we want a "one subfolder per language" layout
then all language-specific files should be moved
for python, that would be `setup.cfg` and `setup.py`

for my taste, the current layout is simpler
because build scripts dont need `cd py/` etc

**Comment by mkoeppe** [comment]
> the current filesystem layout assumes that the package is installed from the project root

Yes, but `pip install . ` from the project root does not work, with the reported error.

**Comment by mkoeppe** [comment]
> where `py.src.gnumake_tokenpool.tokenpool.__version__` should work

Note that your setup.cfg already declares where in the tree to find packages: namely `where=py/src`.
`gnumake_tokenpool.tokenpool.__version__` provides the full module name.

**Comment by milahu** [comment]
> `pip install . ` from the project root does not work

aah. i have re-merged ba838b031da2f20af237159ad6e91ada038ef921. sorry 4 noise. thanks!

**Comment by mkoeppe** [comment]
No worries, thanks!

**Comment by mkoeppe** [comment]
Would you consider tagging a python release and pushing to PyPI?

**Comment by milahu** [comment]
could you do that if i add you as maintainer here?

im not a big fan of pypi/npm/... so im not familiar with the process

**Comment by mkoeppe** [comment]
Sure, no problem

**Comment by mkoeppe** [comment]
https://pypi.org/project/gnumake-tokenpool/0.0.3/

**Comment by milahu** [comment]
thanks : )

i have [updated](https://github.com/milahu/gnumake-tokenpool/commit/596bffbe15d1e0367770f7436e8630a477dbd6ad) py/readme.md

**Pull request merged**
