### PR TITLE
Add CMake setup, test and CI for CC library

### PR DESCRIPTION
**Pull request by bbannier**

### CODE REVIEW

**Comment by bbannier** [comment]
This branch is based on #13 which I'd be interested in regardless of whether the CMake setup and CI changes go in or not.

**Comment by milahu** [comment]
looks harmless. is this ready to merge?

the `cc` code is outdated, see #2
maybe the upstream `cc` code already has these changes?

**Comment by bbannier** [comment]
> looks harmless. is this ready to merge?
> 
> the `cc` code is outdated, see #2 maybe the upstream `cc` code already has these changes?

This was intended to be ready to merge, but for the overlapping commit #13 I didn't know or look into #2 (TBH, not even sure of the exact provenance of the files in this repo).

**Comment by milahu** [comment]
> not even sure of the exact provenance of the files in this repo

i added commit mappings to #2 - see `TODO merge`

**Pull request merged**
